<?php

/**
 * @file
 * Support module for YAML form related testing.
 */

/**
 * Implements hook_theme().
 */
function yamlform_test_theme() {
  return [
    'yamlform_handler_test_summary' => [
      'variables' => ['settings' => NULL, 'handler' => []],
    ],
  ];
}

/**
 * Implements hook_yamlform_options_YAMLFORM_OPTIONS_ID_alter().
 */
function yamlform_test_yamlform_options_test_alter(array &$options, array &$element) {
  // Set three options.
  $options['one'] = 'one';
  $options['two'] = 'two';
  $options['three'] = 'three';
}
