metatag.metatag_tag.fb_admins:
  type: label
  label: 'Facebook Admins'
metatag.metatag_tag.fb_app_id:
  type: label
  label: 'Facebook App ID'
metatag.metatag_tag.fb_pages:
  type: label
  label: 'Facebook Pages'
