# Config schema for Panelizer.

core.entity_view_display.*.*.*.third_party.panelizer:
  type: mapping
  mapping:
    enable:
      type: boolean
      description: 'Is Panelizer enabled?'
    custom:
      type: boolean
      description: 'Are custom overrides allowed?'
    displays:
      type: sequence
      description: 'Default displays'
      sequence:
        type: display_variant.plugin.panels_variant
        description: 'Default display'

