config_devel.settings:
  path: '/admin/config/development/config_devel'
  defaults:
    _form: 'Drupal\config_devel\Form\ConfigDevelSettingsForm'
    _title: 'Config Devel'
  requirements:
    _permission: 'import configuration'
