<?php

/**
 * @file
 * Contains cr_teaser.module..
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_teaser_link_colour.
 *
 * @see options_allowed_values()
 */
function field_teaser_link_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
		'btn--red' => t('Red'),
		'btn--blue' => t('Blue'),
		'btn--yellow' => t('Yellow'),
		'btn--green' => t('Green'),
		'btn--teal' => t('Teal'),
		'btn--royal-blue' => t('Royal blue'),
		'btn--purple' => t('Purple'),
		'btn--pink' => t('Pink'),
		'btn--white' => t('White'),
  ];
  return $values;
}
