# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: php

# The runtime the application uses.
type: "php:7.0"

# Configuration of the build of this application.
build:
    flavor: drupal

# The build-time dependencies of the app.
dependencies:
    php:
        drush/drush: "^8.0"
        phing/phing: "*"
    nodejs:
        grunt-cli: "~0.1.13"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"
    solr: "solr:solr"
#    redis: "redis:redis"

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        "/":
            # The folder to serve static assets for this location from.
            # (Relative to the application root.)
            root: ""

            # How long to allow static assets from this location to be cached.
            # (Can be a time or -1 for no caching. Times can be suffixed with
            # "ms" (milliseconds), "s" (seconds), "m" (minutes), "h" (hours),
            # "d" (days), "w" (weeks), "M" (months, 30d) or "y" (years, 365d).)
            expires: -1

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            # (Can be true, false or a URI path string.)
            passthru: "/index.php"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/sites/default/files": "shared:files/files"
    "/sites/default/sync": "shared:files/config_sync"
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"
    "/drush-backups": "shared:files/drush-backups"
    "/vendor": "shared:files/vendor"
    "/node_modules": "shared:files/node_modules"
    "/.npm": "shared:files/.npm"
    "/.bundle": "shared:files/.bundle"
    "/.gem": "shared:files/.gem"
    "/Gemfile.lock": "shared:files/Gemfile.lock"
    "/profiles/cr/themes/custom/campaign_base/js": "shared:files/js"
    "/profiles/cr/themes/custom/campaign_base/css": "shared:files/css"
    "/profiles/cr/themes/custom/campaign_base/ie9-css": "shared:files/ie9-css"
    "/profiles/cr/themes/custom/campaign_base/styleguide": "shared:files/styleguide"
    "/profiles/cr/themes/custom/campaign_base/images/generated": "shared:files/images_generated"
    "/profiles/cr/.sass-cache": "shared:files/.sass-cache"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # We run deploy hooks after your application has been deployed and started.
    deploy: |
      set -e

      composer install --no-progress --prefer-dist -o
      npm install
      cd profiles/cr
      bundle install --path vendor/bundle --frozen --without craft
      bundle exec grunt build
      cd ../../

      # Re-install the site if this hasn't been installed yet for this branch, or we are on develop
      if [ $PLATFORM_ENVIRONMENT = "develop" ] || [ ! -f tmp/$PLATFORM_ENVIRONMENT.installed ]; then
        echo ">>> Re-installing Campaign profile"
        drush sql-drop -y
        drush si cr -y --account-pass='admin' install_configure_form.update_status_module='[FALSE, FALSE]' -y
        touch "tmp/${PLATFORM_ENVIRONMENT}.installed"
        drush cr
        phing user:create
        echo ">>> End re-installing Campaign profile"
      else
        echo ">>> No re-installation of the profile required, just a simple update!"
        drush cr
      fi


# The configuration of scheduled execution.
crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
