stage_file_proxy.settings:
  type: mapping
  label: 'Stage file proxy settings'
  mapping:
    hotlink:
      type: booleam
      label: "Hotlink"
    origin:
      type: string
      label: "Origin"
    origin_dir:
      type: booelan
      label: "Origin dir"
    use_imagecache_root:
      type: booelan
      label: "Use imagecache root"
"
