<?php

/**
 * @file
 * Test specific changes for the colorbox tests in VEF.
 */
use Drupal\Core\Site\Settings;

/**
 * Implements hook_library_alter().
 */
function video_embed_field_colorbox_test_library_info_alter(&$libraries, $extension) {
  if ($extension !== 'colorbox') {
    return;
  }
  foreach ($libraries['colorbox']['js'] as $key => $library) {
    $libraries['colorbox']['js']['/' . Settings::get('file_public_path') . $key] = $library;
    unset($libraries['colorbox']['js'][$key]);
  }
}
