field.widget.third_party.entity_browser_entity_form:
  type: mapping
  label: 'IEF entity browser existing functionality'
  mapping:
    entity_browser_id:
      type: string
      label: ID of entity browser to be used as replacement for autocomplete field
