pathauto.pattern:
  type: config_object
  mapping:
    patterns:
      type: sequence
      sequence:
        type: mapping
        mapping:
          default:
            type: string
          bundles:
            type: sequence
            sequence:
              type: mapping
              mapping:
                default:
                  type: string
                languages:
                  type: sequence
                  sequence:
                    type: string


pathauto.settings:
  type: config_object
  mapping:
    punctuation:
      type: sequence
      sequence:
        type: integer
    verbose:
      type: boolean
    separator:
      type: string
    max_length:
      type: integer
    max_component_length:
      type: integer
    transliterate:
      type: boolean
    reduce_ascii:
      type: boolean
    ignore_words:
      type: string
    case:
      type: boolean
    ignore_words:
      type: string
    update_action:
      type: integer

action.configuration.pathauto_update_alias:
  type: action_configuration_default
  label: 'Update URL-Alias'
