<?php

/**
 * @file
 * Cards row paragraph type.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_cr_cards_background.
 *
 * @see options_allowed_values()
 */
function cr_cards_field_cr_cards_background(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--white' => t('White'),
    'bg--cream-grey' => t('Cream-Grey'),
    'bg--dark-orchid' => t('Dark-Orchid'),
  ];
  return $values;
}
