<?php

/**
 * @file
 * CR partner module.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_background_colour.
 *
 * @see options_allowed_values()
 */
function cr_partner_field_background_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--white' => t('White'),
    'bg--black' => t('Black'),
    'bg--red' => t('Red'),
    'bg--blue' => t('Blue'),
    'bg--yellow' => t('Yellow'),
    'bg--green' => t('Green'),
    'bg--teal' => t('Teal'),
    'bg--royal-blue' => t('Royal blue'),
    'bg--pink' => t('Pink'),
    'bg--purple' => t('Purple'),
    'bg--jasper-grey' => t('Jasper grey'),
    'bg--gainsboro-grey' => t('Gainsboro grey'),
    'bg--light-grey' => t('Light grey'),
    'bg--smoke-grey' => t('Smoke grey'),
  ];
  return $values;
}

/**
 * Options callback for field_partner_weight.
 *
 * @see options_allowed_values()
 */
function cr_partner_field_partner_weight(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    -10 => t('-10'),
    -9 => t('-9'),
    -8 => t('-8'),
    -7 => t('-7'),
    -6 => t('-6'),
    -5 => t('-5'),
    -4 => t('-4'),
    -3 => t('-3'),
    -2 => t('-2'),
    -1 => t('-1'),
    0 => t('0'),
    1 => t('1'),
    2 => t('2'),
    3 => t('3'),
    4 => t('4'),
    5 => t('5'),
    6 => t('6'),
    7 => t('7'),
    8 => t('8'),
    9 => t('9'),
    10 => t('10'),
  ];
  return $values;
}
