<?php

/**
 * @file
 * CR partner module.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_background_colour.
 *
 * @see options_allowed_values()
 */
function cr_partner_field_background_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--white' => t('White'),
    'bg--black' => t('Black'),
    'bg--red' => t('Red'),
    'bg--sky-blue' => t('Sky blue'),
    'bg--yellow' => t('Yellow'),
    'bg--green' => t('Green'),
    'bg--teal' => t('Teal'),
    'bg--royal-blue' => t('Royal blue'),
    'bg--pink' => t('Pink'),
    'bg--purple' => t('Purple'),
    'bg--jasper-grey' => t('Jasper grey'),
    'bg--gainsboro-grey' => t('Gainsboro grey'),
    'bg--light-grey' => t('Light grey'),
    'bg--smoke-grey' => t('Smoke grey'),
  ];
  return $values;
}
