focal_point.settings:
  type: config_object
  label: 'Focal point settings'
  mapping:
    crop_type:
      type: string
      label: 'Crop type to be used with Focal point'
    default_value:
      type: string
      label: 'The default value to use for focal point when none is specified'
