metatag_open_graph.metatag_tag.og_country_name:
  type: label
  label: 'Open Graph: Country name'
metatag_open_graph.metatag_tag.og_description:
  type: label
  label: 'Open Graph: Description'
metatag_open_graph.metatag_tag.og_determiner:
  type: label
  label: 'Open Graph: Determiner'
metatag_open_graph.metatag_tag.og_email:
  type: label
  label: 'Open Graph: Email'
metatag_open_graph.metatag_tag.og_fax_number:
  type: label
  label: 'Open Graph: Fax number'
metatag_open_graph.metatag_tag.og_image:
  type: label
  label: 'Open Graph: Image height'
metatag_open_graph.metatag_tag.og_image:
  type: label
  label: 'Open Graph: Image'
metatag_open_graph.metatag_tag.og_image_secure_url:
  type: label
  label: 'Open Graph: Image secure URL'
metatag_open_graph.metatag_tag.og_image_type:
  type: label
  label: 'Open Graph: Image type'
metatag_open_graph.metatag_tag.og_image:
  type: label
  label: 'Open Graph: Image (URL)'
metatag_open_graph.metatag_tag.og_image_width:
  type: label
  label: 'Open Graph: Image width'
metatag_open_graph.metatag_tag.og_image_url:
  type: label
  label: 'Open Graph: Image URL'
metatag_open_graph.metatag_tag.og_latitude:
  type: label
  label: 'Open Graph: Latitude'
metatag_open_graph.metatag_tag.og_Locale:
  type: label
  label: 'Open Graph: Locale'
metatag_open_graph.metatag_tag.og_locale_alternative:
  type: label
  label: 'Open Graph: Alternative locale'
metatag_open_graph.metatag_tag.og_locality:
  type: label
  label: 'Open Graph: Locality'
metatag_open_graph.metatag_tag.og_longitude:
  type: label
  label: 'Open Graph: Longitude'
metatag_open_graph.metatag_tag.og_phone_number:
  type: label
  label: 'Open Graph: Phone number'
metatag_open_graph.metatag_tag.og_region:
  type: label
  label: 'Open Graph: Region'
metatag_open_graph.metatag_tag.og_site_name:
  type: label
  label: 'Open Graph: Site name'
metatag_open_graph.metatag_tag.og_street_address:
  type: label
  label: 'Open Graph: Street address'
metatag_open_graph.metatag_tag.og_title:
  type: label
  label: 'Open Graph: Title'
metatag_open_graph.metatag_tag.og_type:
  type: label
  label: 'Open Graph: Type'
metatag_open_graph.metatag_tag.og_updated_time:
  type: label
  label: 'Open Graph: Updated time'
metatag_open_graph.metatag_tag.og_url:
  type: label
  label: 'Open Graph: URL'
