checks:
    php:
        avoid_fixme_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_perl_style_comments: true
        avoid_superglobals: true
        avoid_todo_comments: true
        avoid_usage_of_logical_operators: true
        blank_line_after_namespace_declaration: true
        classes_in_camel_caps: true
        code_rating: true
        coding_standard:
            name: Drupal
        duplication: true
        encourage_postdec_operator: true
        encourage_single_quotes: true
        fix_line_ending: true
        fix_php_opening_tag: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        line_length:
            max_length: '120'
        more_specific_types_in_doc_comments: true
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9]*$'
            abstract_class_name: ^Abstract|Base|Factory$
            utility_class_name: 'Utils?$'
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^[A-Z][a-zA-Z0-9]*$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
            isser_method_name: '^(?:is|has|should|may|supports)'
        newline_at_end_of_file: true
        no_exit: true
        no_global_keyword: true
        no_goto: true
        no_long_variable_names:
            maximum: '20'
        no_mixed_inline_html: true
        no_short_method_names:
            minimum: '3'
        no_short_variable_names:
            minimum: '3'
        no_underscore_prefix_in_methods: true
        no_underscore_prefix_in_properties: true
        one_class_per_file: true
        optional_parameters_at_the_end: true
        param_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        php5_style_constructor: true
        phpunit_assertions: true
        prefer_while_loop_over_for_loop: true
        properties_in_camelcaps: true
        psr2_class_declaration: false
        psr2_control_structure_declaration: false
        psr2_switch_declaration: false
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        require_braces_around_control_structures: true
        return_doc_comment_if_not_inferrable: true
        return_doc_comments: true
        security_vulnerabilities: true
        side_effects_or_types: true
        simplify_boolean_return: true
        single_namespace_per_use: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true

filter:
    excluded_paths:
      - src/Tests
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            before_parentheses:
                closure_definition: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: upper
