<?php

/**
 * @file
 * BG Single Message paragraph type.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_cr_story_row_bg_col.
 *
 * @see options_allowed_values()
 */
function cr_story_field_cr_story_row_bg_col(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--white' => t('White'),
  ];
  return $values;
}

/**
 * Options callback for field_cr_story_fundraiser_bg_col.
 *
 * @see options_allowed_values()
 */
function cr_story_field_cr_story_fundraiser_bg_col(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--white' => t('White'),
  ];
  return $values;
}
