<?php

/**
 * @file
 * Story row paragraph type.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_cr_story_row_bg_col.
 *
 * @see options_allowed_values()
 */
function cr_story_field_cr_story_row_bg_col(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
   	'bg--white' => t('White'),
    'bg--black' => t('Black'),
    'bg--red' => t('Red'),
    'bg--blue' => t('Blue'),
    'bg--yellow' => t('Yellow'),
    'bg--green' => t('Green'),
    'bg--teal' => t('Teal'),
    'bg--royal-blue' => t('Royal blue'),
    'bg--pink' => t('Pink'),
    'bg--purple' => t('Purple'),
    'bg--jasper-grey' => t('Jasper grey'),
    'bg--gainsboro-grey' => t('Gainsboro grey'),
    'bg--light-grey' => t('Light grey'),
    'bg--smoke-grey' => t('Smoke grey'),
    'bg--dark-blue' => t('Dark blue'),
  ];
  return $values;
}

/**
 * Options callback for field_cr_story_fundraiser_bg_col.
 *
 * @see options_allowed_values()
 */
function cr_story_field_cr_story_fundraiser_bg_col(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--red' => t('Red'),
    'bg--blue' => t('Blue'),
    'bg--yellow' => t('Yellow'),
    'bg--pink' => t('Pink'),
  ];
  return $values;
}
