source 'https://rubygems.org'

ruby '1.9.3'

# Sass, Compass and extensions.
gem 'sass', '3.4.5'           # Sass.
gem 'sass-globbing'           # Import Sass files based on globbing pattern.
gem 'compass'                 # Framework built on Sass.
gem 'compass-validator'       # So you can `compass validate`.
gem 'compass-normalize'       # Compass version of normalize.css.
gem 'compass-rgbapng'         # Turns rgba() into .png's for backwards compatibility.
gem 'toolkit'                 # Compass utility from the fabulous Snugug.
gem 'breakpoint'              # Manages CSS media queries.
gem 'oily_png'                # Faster Compass sprite generation.
gem 'css_parser'              # Helps `compass stats` output statistics.
gem 'bootstrap-sass'          # Include the boostrap gem

gem 'sass-rails', '~> 5.0.0'
gem 'susy'

gem 'compass-rails', '~> 2.0.0'

# Guard
gem 'guard'                   # Guard event handler.
gem 'guard-compass'           # Compile on sass/scss change.
gem 'guard-livereload'        # Browser reload.
gem 'yajl-ruby'               # Faster JSON with LiveReload in the browser.

# Dependency to prevent polling. Setup for multiple OS environments.
# Optionally remove the lines not specific to your OS.
# https://github.com/guard/guard#efficient-filesystem-handling
gem 'rb-inotify', '~> 0.9', :require => false      # Linux
gem 'rb-fsevent', :require => false                # Mac OSX
gem 'rb-fchange', :require => false                # Windows

# Add Hologram - markdown based documentation system for style guides.
# http://trulia.github.io/hologram
# gem 'hologram'

# Add  Guard Hologram - uses guard to monitor changes to your hologram project
# and rebuilds your style guide on the fly as you make changes.
# https://github.com/kmayer/guard-hologram
# gem 'guard-hologram', :require => false

