<?php

/**
 * @file
 * Contains cr_iframe.module..
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Implements hook_page_attachments().
 */
function cr_iframe_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'cr_iframe/cr_iframe';
}

/**
 * Options callback for field_cr_iframe_embedded_bg.
 *
 * @see options_allowed_values()
 */
function cr_iframe_field_cr_iframe_embedded_bg(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.config_management.color_service')->getStandardColoursArray();
}

/**
 * Options callback for cr_iframe_field_cr_iframe_layout.
 *
 * @see options_allowed_values()
 */
function cr_iframe_field_cr_iframe_layout(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'full-width' => t('Full width'),
    'ten-column' => t('10 columns'),
    'eight-column' => t('8 columns'),
  ];
  return $values;
}

