<?php

/**
 * @file
 * BG Single Message paragraph type.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_bg_single_msg_bg_colour.
 *
 * @see options_allowed_values()
 */
function cr_rich_text_paragraph_field_bg_single_msg_bg_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.colours.colour_service')->getStandardColoursArray();
}

/**
 * Options callback for field_bg_single_msg_layout.
 *
 * @see options_allowed_values()
 */
function cr_rich_text_paragraph_field_bg_single_msg_layout(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--left' => t('Left'),
    'bg--centre' => t('Centre'),
    'bg--right' => t('Right'),
  ];
  return $values;
}
