<?php

/**
 * @file
 * Contains cr_user.module..
 */

/**
 * Hook social_links_alter, used to alter default socil links.
 *
 * @return array
 *   Altered array of links.
 */
function cr_social_social_links_alter($links) {
  // Remove un used links.
  unset($links['googleplus']);
  unset($links['email']);

  // Set SVGs to use.
  $links['facebook']['svg'] = 'social-link-facebook';
  $links['twitter']['svg'] = 'social-link-twitter';

  return $links;
}
