 # Schema for the configuration files of the Purge module.
purge_queuer_coretags.settings:
  type: config_object
  label: 'Core Tags Queuer settings.'
  mapping:
    blacklist:
      label: 'A list of tag prefixes that should not be queued.'
      type: sequence
      translatable: false
      sequence:
        type: string
        label: 'Prefix string with which tags should not start with.'
        translatable: false
