# Schema for the configuration files of the Redirect module.

redirect.settings:
  type: config_entity
  label: 'Redirect settings'
  mapping:
    canonical:
      type: boolean
      label: 'Redirect from non-canonical URLs to the canonical URLs.'
    auto_redirect:
      type: boolean
      label: 'Automatically create redirects when URL aliases are changed.'
    default_status_code:
      type: integer
      label: 'Default redirect status'
    passthrough_querystring:
      type: boolean
      label: 'Retain query string through redirect.'
    warning:
      type: boolean
      label: 'Display a warning message to users when they are redirected.'
    nonclean_to_clean:
      type: boolean
      label: 'Redirect from non-clean URLs to clean URLs.'
    ignore_admin_path:
      type: boolean
      label: 'Allow redirections on admin paths.'
    frontpage_redirect:
      type: boolean
      label: 'Redirect from paths like index.php and /node to the root directory.'
    deslash:
      type: boolean
      label: 'Remove trailing slashes from paths.'
    trailing_zero:
      type: integer
      label: 'Remove Trailing Zero Argument'
    access_check:
      type: boolean
      label: 'Menu Access Checking'
    normalize_aliases:
      type: boolean
      label: 'Case Sensitive URL Checking'
    content_location_header:
      type: boolean
      label: 'Set Content Location Header'
    term_path_handler:
      type: boolean
      label: 'Taxonomy Term Path Handler'