name: Configuration Update Reports
type: module
description: 'Adds an updates report and revert functionality to configuration management'
# core: 8.x
configure: config_update.report
dependencies:
  - config_update
  - config

# Information added by Drupal.org packaging script on 2016-03-08
version: '8.x-1.1'
core: '8.x'
project: 'config_update'
datestamp: 1457466840
