<?php

/**
 * @file
 * CR landing page module.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_landing_background_colour.
 *
 * @see options_allowed_values()
 */
function cr_landing_page_field_landing_background_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.colours.color_service')->getStandardColoursArray();
}

/**
 * Options callback for field_landing_copy_position_alig.
 */
function cr_landing_page_field_landing_copy_position_alig(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'promo-header__content-inner--left' => t('Left'),
    'promo-header__content-inner--centre' => t('Centre'),
    'promo-header__content-inner--right' => t('Right'),
  ];
  return $values;
}

/**
 * Implements hook_page_attachments().
 */
function cr_landing_page_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'campaign_base/vide';
}
