<?php

/**
 * @file
 * Single message row paragraph type.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_single_msg_bg.
 *
 * @see options_allowed_values()
 */
function cr_single_msg_field_single_msg_bg(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.config_management.color_service')->getStandardColoursArray();
}

/**
 * Options callback for field_single_msg_body_bg_colour.
 *
 * @see options_allowed_values()
 */
function cr_single_msg_field_single_msg_body_bg_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.config_management.color_service')->getStandardColoursArray();
}

/**
 * Options callback for field_single_msg_layout_variant.
 *
 * @see options_allowed_values()
 */
function cr_single_msg_field_single_msg_layout_variant(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'copy-left' => t('Copy Left'),
    'copy-right' => t('Copy Right'),
    'feature-copy-left' => t('Feature Copy Left'),
    'feature-copy-right' => t('Feature Copy Right'),
    'copy-only' => t('Copy Only'),
  ];
  return $values;
}

/**
 * Options callback for field_single_msg_padding_option
 *
 * @see options_allowed_values()
 */
function cr_single_msg_field_single_msg_padding_option(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'default-padding' => t('Default'),
    'negative-top' => t('Reduce top padding'),
    'negative-bottom' => t('Reduce bottom padding'),
    'no-top-padding' => t('Remove top padding'),
    'no-bottom-padding' => t('Remove bottom padding'),
    'no-padding' => t('Remove top and bottom padding'),
  ];
  return $values;
}
