<?php

/**
 * @file
 * CR landing page module.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_landing_background_colour.
 *
 * @see options_allowed_values()
 */
function cr_landing_page_field_landing_background_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--white' => t('White'),
    'bg--black' => t('Black'),
    'bg--red' => t('Red'),
    'bg--blue' => t('Blue'),
    'bg--yellow' => t('Yellow'),
    'bg--green' => t('Green'),
    'bg--teal' => t('Teal'),
    'bg--royal-blue' => t('Royal blue'),
    'bg--pink' => t('Pink'),
    'bg--purple' => t('Purple'),
    'bg--jasper-grey' => t('Jasper grey'),
    'bg--gainsboro-grey' => t('Gainsboro grey'),
    'bg--light-grey' => t('Light grey'),
    'bg--smoke-grey' => t('Smoke grey'),
    'bg--dark-blue' => t('Dark blue'),
  ];
  return $values;
}

/**
 * Options callback for field_landing_copy_position_alig.
 */
function cr_landing_page_field_landing_copy_position_alig(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'promo-header__content-inner--left' => t('Left'),
    'promo-header__content-inner--centre' => t('Centre'),
    'promo-header__content-inner--right' => t('Right'),
  ];
  return $values;
}

/**
 * Implements hook_page_attachments().
 */
function cr_landing_page_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'campaign_base/vide';
}
