<?php

/**
 * @file
 * Contains social_links.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use \Drupal\social_links\Plugin\Social\SocialLinks;

/**
 * Implements hook_help().
 */
function social_links_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_links module.
    case 'help.page.social_links':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Social Links provides social share links on entities.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function social_links_entity_extra_field_info() {
  $entity_manager = \Drupal::entityManager();
  $entity_types = $entity_manager->getDefinitions();
  $extra = [];

  foreach (array_keys($entity_types) as $entity_type) {
    $bundles = $entity_manager->getBundleInfo($entity_type);
    foreach (array_keys($bundles) as $bundle) {
      $extra[$entity_type][$bundle]['display']['social_links'] = array(
        'label' => t('Social Links'),
        'description' => t('description'),
        'weight' => 0,
        'visible' => FALSE,
      );
    }
  }

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function social_links_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('social_links')) {
    $social_links = new SocialLinks();
    $build['social_links'] = $social_links->renderLinks($entity);
  }
}

/**
 * Social links callback function.
 */
function social_links_provider_email(&$link_options, $entity) {
  $subject = '';
  $body = $subject . '%0D' . $link_options['path'];
  $link_options['path'] = 'mailto:?subject=' . $subject . '&body=' . $body;
}

/**
 * Social links callback function.
 */
function social_links_provider_popup(&$link_options, $entity) {
  $link_options['attributes']['class'][] = 'social-link-popup';
}
