"plugin.plugin_configuration.search_api_datasource.entity:*":
  type: mapping
  label: 'Entity datasource configuration'
  mapping:
    default:
      type: string
      label: 'Decides if we want to include or exclude the selected bundles.'
    bundles:
      type: sequence
      label: 'The selected bundles'
      sequence:
        type: string
        label: 'An entity bundle'
    languages:
      type: sequence
      label: 'The selected languages'
      sequence:
        type: string
        label: 'An entity language'
