# Base definitions for processors

search_api.default_processor_configuration:
  type: mapping
  label: 'Default processor configuration'
  mapping:
    weights:
      type: sequence
      label: 'The processor''s weights for the different processing stages'
      sequence:
        type: integer
        label: 'The processor''s weight for this stage'

search_api.fields_processor_configuration:
  type: search_api.default_processor_configuration
  label: 'Fields processor configuration'
  mapping:
    fields:
      type: sequence
      label: 'The selected fields'
      sequence:
        type: string
        label: 'Selected field'

# Default for any processor without specific configuration
plugin.plugin_configuration.search_api_processor.*:
  type: search_api.default_processor_configuration

# Definitions for individual processors

plugin.plugin_configuration.search_api_processor.highlight:
  type: search_api.default_processor_configuration
  label: 'Highlight processor configuration'
  mapping:
    prefix:
      type: string
      label: 'Text/HTML that will be prepended to all occurrences of search keywords in highlighted text'
    suffix:
      type: string
      label: 'Text/HTML that will be appended to all occurrences of search keywords in highlighted text'
    excerpt:
      type: boolean
      label: 'When enabled, an excerpt will be created for searches with keywords, containing all occurrences of keywords in a fulltext field.'
    excerpt_length:
      type: integer
      label: 'The requested length of the excerpt, in characters'
    exclude_fields:
      type: sequence
      label: 'Fields excluded from excerpt'
      sequence:
        type: string
        label: 'An excluded field''s ID'
    highlight:
      type: string
      label: 'Defines whether returned fields should be highlighted (always/if returned/never).'

plugin.plugin_configuration.search_api_processor.html_filter:
  type: search_api.fields_processor_configuration
  label: 'HTML filter processor configuration'
  mapping:
    title:
      type: boolean
      label: 'Title'
    alt:
      type: boolean
      label: 'Alt'
    tags:
      type: sequence
      label: 'Tag boosts'
      sequence:
        type: integer
        label: Boost

plugin.plugin_configuration.search_api_processor.ignorecase:
  type: search_api.fields_processor_configuration
  label: 'Ignore case processor configuration'

plugin.plugin_configuration.search_api_processor.ignore_character:
  type: search_api.fields_processor_configuration
  label: 'Ignore Character processor configuration'
  mapping:
    ignorable:
      type: string
      label: 'Regular expression for characters it should ignore to stem'
    strip:
      type: mapping
      label: 'Configurable characters to ignore'
      mapping:
        character_sets:
          type: sequence
          label: 'Configuration of the character sets'
          sequence:
            type: ignore
            label: 'Character set'

plugin.plugin_configuration.search_api_processor.role_filter:
  type: search_api.default_processor_configuration
  label: 'Role filter processor configuration'
  mapping:
    default:
      type: boolean
      label: 'Default'
    roles:
      type: sequence
      label: 'The selected roles'
      sequence:
        type: string
        label: 'The role name'

plugin.plugin_configuration.search_api_processor.stopwords:
  type: search_api.fields_processor_configuration
  label: 'Stopwords processor configuration'
  mapping:
    stopwords:
      type: sequence
      label: 'entered stopwords'
      sequence:
        type: string
        label: Stopword

plugin.plugin_configuration.search_api_processor.tokenizer:
  type: search_api.fields_processor_configuration
  label: 'Tokenizer processor configuration'
  mapping:
    spaces:
      type: string
      label: 'Regular expression for spaces'
    ignorable:
      type: string
      label: 'Regular expression for ignorables'
    overlap_cjk:
      type: integer
      label: 'Defines if simple CJK handling should be enabled.'
    minimum_word_size:
      type: string
      label: 'Defines the minimum word size'

plugin.plugin_configuration.search_api_processor.transliteration:
  type: search_api.fields_processor_configuration
  label: 'Transliteration processor configuration'

# Definitions for property configuration

search_api.property_configuration.*:
  type: mapping
  label: 'Default field configuration'
  mapping: {}

search_api.property_configuration.aggregated_field:
  type: mapping
  label: 'Aggregated field configuration'
  mapping:
    type:
      type: string
      label: 'The type of the aggregation'
    fields:
      type: sequence
      label: 'The properties to be aggregated'
      sequence:
        type: string
        label: 'A property that should be part of the aggregation'

search_api.property_configuration.rendered_item:
  type: mapping
  label: 'Rendered item processor configuration'
  mapping:
    roles:
      type: sequence
      label: 'The selected roles'
      sequence:
        type: string
        label: 'The user roles which will be active when the entity is rendered'
    view_mode:
      type: sequence
      label: 'The selected view modes for each datasource, by bundle'
      sequence:
        type: sequence
        label: 'The selected view modes for the datasource, by bundle'
        sequence:
          type: string
          label: 'The view mode used to render the entity for the specified bundle'
