<?php

use Drupal\cr_article\Service\ArticleService;

/**
 * @file
 * News article module adds a content type for your news.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_article_type.
 *
 * @see options_allowed_values()
 */
function cr_article_field_article_type(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.article.article_service')->getArticleTypes();
}

/**
 * Get available fields that are not hidden from aggregation.
 * Implements hook_form_alter().
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function cr_article_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-what-s-going-on-block-1') {
    // Detect whether to limit by press releases or news articles.
    $action = $form['#action'] === '/press-releases' || strpos(\Drupal::service('path.current')->getPath(), 'press-releases') !== -1 ? ArticleService::TYPE_PRESS_RELEASE : ArticleService::TYPE_NEWS;

    // Sort the array by value.
    $form['field_article_category_target_id']['#options'] = \Drupal::service('cr.article.article_service')->getArticleTypeAvailableTaxonomies($action);
  }
}
