<?php

/**
 * @file
 * Content Wall module adds site functionality.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_cw_view_mode.
 *
 * @see options_allowed_values()
 */
function cr_content_wall_field_cw_view_mode(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'cw_1col_l' => t('1 Col - L'),
    'cw_2col_m_m' => t('2 Col - M + M'),
    'cw_2col_s_m' => t('2 Col - S + M'),
    'cw_2col_m_s' => t('2 Col - M + S'),
    'cw_3col_s_s_s' => t('3 Col - S + S + S'),
  ];
  return $values;
}

/**
 * Options callback for field_cw_bg_colour.
 *
 * @see options_allowed_values()
 */
function field_cw_bg_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--white' => t('White'),
    'bg--red' => t('Red'),
    'bg--sky-blue' => t('Sky blue'),
    'bg--yellow' => t('Yellow'),
    'bg--green' => t('Green'),
    'bg--teal' => t('Teal'),
    'bg--royal-blue' => t('Royal blue'),
    'bg--purple' => t('Purple'),
    'bg--pink' => t('Pink'),
    'bg--black' => t('Black'),
    'bg--dark-blue' => t('Dark blue'),
  ];
  return $values;
}

/**
 * Options callback for field_cw_bg_colour.
 *
 * @see options_allowed_values()
 */
function field_cw_link_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'link--red' => t('Red'),
    'link--sky-blue' => t('Sky blue'),
    'link--green' => t('Green'),
    'link--teal' => t('Teal'),
    'link--royal-blue' => t('Royal blue'),
    'link--purple' => t('Purple'),
    'link--pink' => t('Pink'),
    'link--yellow' => t('Yellow'),
    'link--white' => t('White'),
  ];
  return $values;
}
