# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysql:
    type: "mysql:10.0"
    disk: 2048
#
#redis:
#    type: "redis:3.0"
#
solr:
    type: "solr:6.3"
    disk: 1024
    configuration:
        cores:
            mainindex:
                conf_dir: !archive "solr/6.x"
        endpoints:
            main:
                core: mainindex
