plugin.plugin_configuration.search_api_backend.search_api_db:
  type: mapping
  label: 'Search API DB settings'
  mapping:
    database:
      type: 'string'
      label: 'Name of the database we are connecting to'
    min_chars:
      type: 'integer'
      label: 'Minimum length of indexed words'
    partial_matches:
      type: 'boolean'
      label: 'Whether to also search on parts of a word'
    autocomplete:
      type: mapping
      label: Autcomplete configuration
      mapping:
        suggest_suffix:
          type: boolean
          label: Suggest suffix
        suggest_words:
          type: boolean
          label: Suggest words
