jsonapi.resource_info:
  type: config_object
  mapping:
    prefix:
      type: string
      label: 'Prefix'
    schema_prefix:
      type: string
      label: 'Schema prefix'
    id_field:
      type: string
      label: 'API field'
