<?php

/**
 * @file
 * Contains cr_teaser.module..
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_teaser_link_colour.
 *
 * @see options_allowed_values()
 */
function cr_teaser_field_teaser_link_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.colours.colour_service')->getStandardButtonColoursArray();
}

/**
 * Options callback for cr_teaser_field_cr_teaser_bg_colour.
 *
 * @see options_allowed_values()
 */
function cr_teaser_field_teaser_bg_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.colours.colour_service')->getStandardColoursArray();
}
