features.bundle.*:
  type: config_entity
  label: 'Features bundle'
  mapping:
    machine_name:
      type: string
      label: "Machine name"
    name:
      type: string
      label: "Name"
    description:
      type: string
      label: "Description"
    assignments:
      type: ignore
      label: "Assignment"
      # @todo Profile a proper config schema.
    profile_name:
      type: string
      label: "Profile name"
    is_profile:
      type: boolean
      label: "Is install profile"

