paragraphs.paragraphs_type.*:
  type: config_entity
  label: 'Paragraphs type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'

entity_reference_selection.default:paragraph:
  type: entity_reference_selection
  mapping:
    target_bundles_drag_drop:
      type: sequence
      sequence:
        type: mapping
        mapping:
          weight:
            type: integer
          enabled:
            type: boolean
    add_mode:
      type: string
    edit_mode:
      type: string
    title:
      type: string
    title_plural:
      type: string

field.widget.settings.entity_reference_paragraphs:
  type: mapping
  mapping:
    title:
      type: string
    title_plural:
      type: string
    edit_mode:
      type: string
    add_mode:
      type: string
    form_display_mode:
      type: string
