<?php

/**
 * @file
 * Contains view_modes_display.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function view_modes_display_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the view_modes_display module.
    case 'help.page.view_modes_display':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Preview view modes for every entity type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function view_modes_display_theme() {
  $theme = [];

  return $theme;
}
