# The base type all mapping types must extend.
cdn.mapping_base:
  type: mapping
  mapping:
    type:
      type: string
      label: 'CDN mapping type'

# The base type all mapping types that have conditions must extend.
cdn.mapping_with_conditions_base:
  type: cdn.mapping_base
  mapping:
    conditions:
      type: cdn.conditions

# 'simple': a single CDN domain, with conditions.
cdn.mapping.simple:
  type: cdn.mapping_with_conditions_base
  mapping:
    domain:
      type: cdn.domain
      label: 'A single CDN domain.'

# 'auto-balanced': auto-balanced domains, with conditions.
cdn.mapping.auto-balanced:
  type: cdn.mapping_with_conditions_base
  mapping:
    domains:
      type: sequence
      label: 'Multiple CDN domains across which to auto-balance files (in a consistent manner).'
      sequence:
        type: cdn.domain
        label: 'A CDN domain.'

# 'complex': a mapping that allows to conditionally use different CDN domains.
cdn.mapping.complex:
  type: cdn.mapping_base
  label: 'Complex'
  mapping:
    fallback_domain:
      type: cdn.domain
      nullable: true
      label: 'The optional fallback CDN domain to use when none of the other domains are selected.'
    domains:
      type: sequence
      sequence:
        # @todo How to prevent recursion? This should only accept 'simple', 'auto-balanced' and whichever ones are added in the future.
        type: cdn.mapping.[type]
