cdn.conditions:
  type: sequence
  label: 'Conditions'
  sequence:
    type: cdn.condition.[%key]

cdn.condition.extensions:
  type: sequence
  label: 'Allowed file extensions'
  sequence:
    type: string
    label: 'Allowed file extension'
