display_variant.plugin.block_page_layout:
  type: ctools.block_display_variant
  label: 'Block page layout display variant'
  mapping:
    page_title:
      type: string
      label: Page Title
    layout:
      type: string
      label: Layout
    layout_settings:
      type: layout_plugin.settings.[%parent.layout]
      label: Layout settings
