yamlform.admin_settings.third_party.honeypot:
  type: mapping
  label: 'Form test third party settings'
  mapping:
    honeypot:
      type: boolean
      label: 'Protect all forms with Honeypot'
    time_restriction:
      type: boolean
      label: 'Add time limit to all forms'

yamlform.settings.third_party.honeypot:
  type: mapping
  label: 'Form test third party settings'
  mapping:
    honeypot:
      type: boolean
      label: 'Protect all forms with Honeypot'
    time_restriction:
      type: boolean
      label: 'Add time limit to all forms'
