# Schema for the configuration files of the YAML form module.

yamlform.settings:
  type: config_object
  label: 'YAML form settings'
  mapping:
    settings:
      type: mapping
      label: 'Form default settings'
      mapping:
        default_page_base_path:
          type: string
          label: 'Default base path'
        default_form_submit_label:
          type: label
          label: 'Default form submit text'
        default_form_closed_message:
          type: text
          label: 'Default form closed message'
        default_form_exception_message:
          type: text
          label: 'Default form exception message'
        default_preview_next_button_label:
          type: label
          label: 'Default preview button label'
        default_preview_prev_button_label:
          type: label
          label: 'Default previous page button label'
        default_preview_message:
          type: text
          label: 'Default preview message'
        default_draft_button_label:
          type: label
          label: 'Default draft button label'
        default_draft_saved_message:
          type: text
          label: 'Default draft save message'
        default_draft_loaded_message:
          type: text
          label: 'Default draft load message'
        default_confirmation_message:
          type: text
          label: 'Default confirmation message'
        default_limit_total_message:
          type: text
          label: 'Default limit total message'
        default_limit_user_message:
          type: text
          label: 'Default limit user message'
    inputs:
      type: mapping
      label: 'Inputs default settings'
      mapping:
        default_inputs:
          type: string
          label: 'Default inputs'
        default_max_filesize:
          type: string
          label: 'Default maximum upload size'
        default_file_extensions:
          type: string
          label: 'Default allowed file extensions'
    format:
      type: ignore
      label: 'Format default settings'
    mail:
      type: mapping
      label: 'Email default settings'
      mapping:
        default_from_mail:
          type: email
          label: 'Default email from address'
        default_from_name:
          type: label
          label: 'Default email from name'
        default_subject:
          type: label
          label: 'Default email subject'
        default_body_text:
          type: text
          label: 'Default email body (Plain text)'
        default_body_html:
          type: text
          label: 'Default email body (HTML)'
    export:
      type: mapping
      label: 'Export default settings'
      mapping:
        delimiter:
          type: string
          label: 'Delimiter text format'
        header_keys:
          type: string
          label: 'Column header format'
        entity_reference_format:
          type: string
          label: 'Options format'
        options_format:
          type: string
          label: 'Options item format'
        options_item_format:
          type: string
          label: 'Entity reference format'
    batch:
      type: mapping
      label: 'Batch settings'
      mapping:
        default_batch_export_size:
          type: integer
          label: 'Batch export size'
        default_batch_update_size:
          type: integer
          label: 'Batch update size'
        default_batch_delete_size:
          type: integer
          label: 'Batch delete size'
    test:
      type: mapping
      label: 'Test settings'
      mapping:
        types:
          type: text
          label: 'Test types'
        names:
          type: text
          label: 'Test names'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: yamlform.admin_settings.third_party.[%key]

yamlform.yamlform.*:
  type: config_entity
  label: 'YAML form'
  mapping:
    status:
      type: boolean
      label: 'Status'
    id:
      type: string
      label: 'Machine name'
    title:
      type: label
      label: 'Title'
    description:
      type: label
      label: 'Administrative description'
    inputs:
      type: text
      label: 'Inputs (YAML)'
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        page:
          type: boolean
          label: 'Enable page'
        page_submit_path:
          type: string
          label: 'Page submit URL alias'
        page_confirm_path:
          type: string
          label: 'Page confirm URL alias'
        form_submit_label:
          type: label
          label: 'Form submit text'
        form_closed_message:
          type: text
          label: 'Form closed message'
        form_exception_message:
          type: text
          label: 'Form exception message'
        form_prepopulate:
          type: boolean
          label: 'Form prepopulate inputs'
        preview:
          type: integer
          label: 'Enable preview page'
        preview_next_button_label:
          type: label
          label: 'Preview button label'
        preview_prev_button_label:
          type: label
          label: 'Previous page button label'
        preview_message:
          type: text
          label: 'Preview message'
        draft:
          type: boolean
          label: 'Allow your users to save and finish the form later.'
        draft_auto_save:
          type: boolean
          label: 'Automatically save as draft when previewing and when there are validation errors.'
        draft_button_label:
          type: label
          label: 'Draft button label'
        draft_saved_message:
          type: text
          label: 'Draft saved message'
        draft_loaded_message:
          type: text
          label: 'Draft loaded message'
        confirmation_type:
          type: string
          label: 'Confirmation type'
        confirmation_message:
          type: text
          label: 'Confirmation message'
        confirmation_url:
          type: string
          label: 'Confirmation URL'
        limit_total:
          type: integer
          label: 'Limit total submissions'
        limit_total_message:
          type: text
          label: 'Limit total message'
        limit_user:
          type: integer
          label: 'Limit user submissions'
        limit_user_message:
          type: text
          label: 'Limit user message'
        results_disabled:
          type: boolean
          label: 'Results disabled'
    access:
      type: mapping
      label: 'Access'
      mapping:
        create:
          type: mapping
          label: 'Create YAML form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        view_any:
          type: mapping
          label: 'View any YAML form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        update_any:
          type: mapping
          label: 'Update any YAML form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        delete_any:
          type: mapping
          label: 'Delete any YAML form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        purge_any:
          type: mapping
          label: 'Purge any YAML form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        view_own:
          type: mapping
          label: 'View own YAML form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        update_own:
          type: mapping
          label: 'Update own YAML form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        delete_own:
          type: mapping
          label: 'Delete own YAML form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
    handlers:
      type: sequence
      label: 'YAML form handlers'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          handler_id:
            type: string
          label:
            type: label
          status:
            type: boolean
          weight:
            type: integer
          settings:
            type: yamlform.handler.[%parent.id]
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: yamlform.settings.third_party.[%key]

yamlform.handler.*:
  type: mapping
  label: 'Handler settings'

yamlform.handler.email:
  type: mapping
  label: 'Email'
  mapping:
    to_mail:
      label: 'Email to address'
      type: email
    from_mail:
      label: 'Email from address'
      type: email
    from_name:
      label: 'Email from name'
      type: label
    subject:
      label: 'Email subject'
      type: label
    body:
      label: 'Email body'
      type: text
    excluded_inputs:
      type: sequence
      label: 'Exclude inputs'
      sequence:
        type: string
        label: 'Input name'
    html:
      type: boolean
      label: 'HTML'
    attachments:
      type: boolean
      label: 'Attachments'
    debug:
      type: boolean
      label: 'Enable debugging'

yamlform.yamlform_options.*:
  type: config_entity
  label: 'YAML form options'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    options:
      type: text
      label: 'Options (YAML)'

block.settings.yamlform_block:
  type: block_settings
  label: 'YAML form block'
  mapping:
    yamlform_id:
      type: text
      label: 'YAML form'
    default_data:
      type: text
      label: 'Default YAML form submission data'

# Schema for the configuration of the YAML form field type.

field.storage_settings.yamlform:
  type: mapping
  label: 'YAML form field storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

base_yamlform_field_field_settings:
  type: mapping
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Entity reference selection settings'

field.field_settings.yamlform:
  type: base_yamlform_field_field_settings
  label: 'YAML form settings'
  mapping:
    default_data:
      type: string
      label: 'Default YAML form submission data'
    status:
      type: boolean
      label: 'Status of the YAML form'

field.widget.settings.yamlform_entity_reference_autocomplete:
  type: mapping
  label: 'YAML form autocomplete display format settings'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Placeholder'

field.formatter.settings.yamlform_entity_reference_entity_view:
  type: mapping
  label: 'Display the referenced YAML form with default submission data.'
