# Schema for the configuration files of the YAML Form module.

yamlform.settings:
  type: config_object
  label: 'Form settings'
  mapping:
    settings:
      type: mapping
      label: 'Form default settings'
      mapping:
        default_page_base_path:
          type: string
          label: 'Default base path'
        default_form_submit_label:
          type: label
          label: 'Default form submit text'
        default_form_closed_message:
          type: text
          label: 'Default form closed message'
        default_form_exception_message:
          type: text
          label: 'Default form exception message'
        default_form_confidential_message:
          type: text
          label: 'Default form confidential message'
        default_form_novalidate:
          type: boolean
          label: 'Disable client-side validation'
        default_form_details_toggle:
          type: boolean
          label: 'Display collapse/expand all details link'
        default_wizard_prev_button_label:
          type: label
          label: 'Default wizard previous page button label'
        default_wizard_next_button_label:
          type: label
          label: 'Default wizard next page button label'
        default_wizard_start_label:
          type: label
          label: 'Default wizard start label'
        default_wizard_complete_label:
          type: label
          label: 'Default wizard complete label'
        default_preview_next_button_label:
          type: label
          label: 'Default preview button label'
        default_preview_prev_button_label:
          type: label
          label: 'Default preview previous page button label'
        default_preview_message:
          type: text
          label: 'Default preview message'
        default_draft_button_label:
          type: label
          label: 'Default draft button label'
        default_draft_saved_message:
          type: text
          label: 'Default draft save message'
        default_draft_loaded_message:
          type: text
          label: 'Default draft load message'
        default_confirmation_message:
          type: text
          label: 'Default confirmation message'
        default_limit_total_message:
          type: text
          label: 'Default limit total message'
        default_limit_user_message:
          type: text
          label: 'Default limit user message'
    elements:
      type: mapping
      label: 'Elements default settings'
      mapping:
        allowed_tags:
          type: string
          label: 'Allowed tags'
        wrapper_classes:
          type: string
          label: 'Wrapper CSS classes'
        classes:
          type: string
          label: 'Element CSS classes'
        default_description_display:
          type: string
          label: 'Default title display'
        default_max_filesize:
          type: string
          label: 'Default maximum upload size'
        default_file_extensions:
          type: string
          label: 'Default allowed file extensions'
        default_google_maps_api_key:
          type: string
          label: 'Default Google Maps API key'
    format:
      type: ignore
      label: 'Format default settings'
    mail:
      type: mapping
      label: 'Email default settings'
      mapping:
        default_from_mail:
          type: email
          label: 'Default email from address'
        default_from_name:
          type: label
          label: 'Default email from name'
        default_subject:
          type: label
          label: 'Default email subject'
        default_body_text:
          type: text
          label: 'Default email body (Plain text)'
        default_body_html:
          type: text
          label: 'Default email body (HTML)'
    export:
      type: mapping
      label: 'Export default settings'
      mapping:
        delimiter:
          type: string
          label: 'Delimiter text format'
        header_format:
          type: string
          label: 'Column header format'
        header_prefix:
          type: boolean
          label: 'Column header prefix'
        header_prefix_key_delimiter:
          type: string
          label: 'Column header prefix key delimiter'
        header_prefix_label_delimiter:
          type: string
          label: 'Column header prefix label delimiter'
        entity_reference_format:
          type: string
          label: 'Options format'
        options_format:
          type: string
          label: 'Options item format'
        options_item_format:
          type: string
          label: 'Entity reference format'
        likert_answers_format:
          type: string
          label: 'Likert answers format'
        signature_format:
          type: string
          label: 'Signature format'
        composite_element_item_format:
          type: string
          label: 'Composite element item format'
    batch:
      type: mapping
      label: 'Batch settings'
      mapping:
        default_batch_export_size:
          type: integer
          label: 'Batch export size'
        default_batch_update_size:
          type: integer
          label: 'Batch update size'
        default_batch_delete_size:
          type: integer
          label: 'Batch delete size'
    test:
      type: mapping
      label: 'Test settings'
      mapping:
        types:
          type: text
          label: 'Test types'
        names:
          type: text
          label: 'Test names'
    ui:
      type: mapping
      label: 'User interface settings'
      mapping:
        video_display:
          type: string
          label: 'Video display'
        dialog_disabled:
          type: boolean
          label: 'Disable dialogs'
        html_editor_disabled:
          type: boolean
          label: 'Disable HTML editor'
        details_save:
          type: boolean
          label: 'Save details open/close state'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: yamlform.admin_settings.third_party.[%key]

yamlform.yamlform.*:
  type: config_entity
  label: 'Forms'
  mapping:
    status:
      type: boolean
      label: 'Status'
    uid:
      type: integer
      label: 'Author'
    template:
      type: boolean
      label: 'Template'
    id:
      type: string
      label: 'Machine name'
    title:
      type: label
      label: 'Title'
    description:
      type: label
      label: 'Administrative description'
    elements:
      type: text
      label: 'Elements (YAML)'
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        page:
          type: boolean
          label: 'Enable page'
        page_submit_path:
          type: string
          label: 'Page submit URL alias'
        page_confirm_path:
          type: string
          label: 'Page confirm URL alias'
        form_submit_label:
          type: label
          label: 'Form submit text'
        form_closed_message:
          type: text
          label: 'Form closed message'
        form_exception_message:
          type: text
          label: 'Form exception message'
        form_confidential:
          type: boolean
          label: 'Form confidential'
        form_confidential_message:
          type: text
          label: 'Form confidential message'
        form_prepopulate:
          type: boolean
          label: 'Form prepopulate elements'
        form_prepopulate_source_entity:
          type: boolean
          label: 'Form prepopulate source entity'
        form_novalidate:
          type: boolean
          label: 'Disable client-side validation'
        form_autofocus:
          type: boolean
          label: 'Autofocus'
        form_details_toggle:
          type: boolean
          label: 'Display collapse/expand all details link'
        wizard_progress_bar:
          type: boolean
          label: 'Show wizard progress bar'
        wizard_progress_pages:
          type: boolean
          label: 'Show wizard progress pages'
        wizard_progress_percentage:
          type: boolean
          label: 'Show wizard progress pages'
        wizard_start_label:
          type: label
          label: 'Wizard start label'
        wizard_complete:
          type: boolean
          label: 'Include confirmation page in progress'
        wizard_complete_label:
          type: label
          label: 'Wizard complete label'
        wizard_prev_button_label:
          type: label
          label: 'Default wizard previous page button label'
        wizard_next_button_label:
          type: label
          label: 'Default wizard next page button label'
        preview:
          type: integer
          label: 'Enable preview page'
        preview_next_button_label:
          type: label
          label: 'Preview button label'
        preview_prev_button_label:
          type: label
          label: 'Previous page button label'
        preview_message:
          type: text
          label: 'Preview message'
        draft:
          type: boolean
          label: 'Allow your users to save and finish the form later.'
        draft_auto_save:
          type: boolean
          label: 'Automatically save as draft when previewing and when there are validation errors.'
        draft_button_label:
          type: label
          label: 'Draft button label'
        draft_saved_message:
          type: text
          label: 'Draft saved message'
        draft_loaded_message:
          type: text
          label: 'Draft loaded message'
        confirmation_type:
          type: string
          label: 'Confirmation type'
        confirmation_url:
          type: string
          label: 'Confirmation URL'
        confirmation_message:
          type: text
          label: 'Confirmation message'
        limit_total:
          type: integer
          label: 'Limit total submissions'
        limit_total_message:
          type: text
          label: 'Limit total message'
        limit_user:
          type: integer
          label: 'Limit user submissions'
        limit_user_message:
          type: text
          label: 'Limit user message'
        entity_limit_total:
          type: integer
          label: 'Entity limit total submissions'
        entity_limit_user:
          type: integer
          label: 'Entity limit user submissions'
        results_disabled:
          type: boolean
          label: 'Results disabled'
        token_update:
          type: boolean
          label: 'Allow updates using token'
    access:
      type: mapping
      label: 'Access'
      mapping:
        create:
          type: mapping
          label: 'Create form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        view_any:
          type: mapping
          label: 'View any form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        update_any:
          type: mapping
          label: 'Update any form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        delete_any:
          type: mapping
          label: 'Delete any form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        purge_any:
          type: mapping
          label: 'Purge any form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        view_own:
          type: mapping
          label: 'View own form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        update_own:
          type: mapping
          label: 'Update own form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
        delete_own:
          type: mapping
          label: 'Delete own form submissions'
          mapping:
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
            users:
              type: sequence
              label: 'Users'
              sequence:
                type: integer
                label: 'User IDs'
    handlers:
      type: sequence
      label: 'Form handlers'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          handler_id:
            type: string
          label:
            type: label
          status:
            type: boolean
          weight:
            type: integer
          settings:
            type: yamlform.handler.[%parent.id]
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: yamlform.settings.third_party.[%key]

yamlform.handler.*:
  type: mapping
  label: 'Handler settings'

yamlform.handler.email:
  type: mapping
  label: 'Email'
  mapping:
    to_mail:
      label: 'Email to address'
      type: email
    bcc_mail:
      label: 'Email Bcc address'
      type: email
    cc_mail:
      label: 'Email Cc address'
      type: email
    from_mail:
      label: 'Email from address'
      type: email
    from_name:
      label: 'Email from name'
      type: label
    subject:
      label: 'Email subject'
      type: label
    body:
      label: 'Email body'
      type: text
    excluded_elements:
      type: sequence
      label: 'Exclude Elements'
      sequence:
        type: string
        label: 'Element name'
    html:
      type: boolean
      label: 'HTML'
    attachments:
      type: boolean
      label: 'Attachments'
    debug:
      type: boolean
      label: 'Enable debugging'

yamlform.yamlform_options.*:
  type: config_entity
  label: 'Form options'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    options:
      type: text
      label: 'Options (YAML)'

block.settings.yamlform_block:
  type: block_settings
  label: 'Forms block'
  mapping:
    yamlform_id:
      type: text
      label: 'Forms'
    default_data:
      type: text
      label: 'Default form submission data'

# Schema for the configuration of the form field type.

field.storage_settings.yamlform:
  type: mapping
  label: 'Form field storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

base_yamlform_field_field_settings:
  type: mapping
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Entity reference selection settings'

field.field_settings.yamlform:
  type: base_yamlform_field_field_settings
  label: 'Form settings'
  mapping:
    default_data:
      type: string
      label: 'Default form submission data'
    status:
      type: boolean
      label: 'Status of the form'

field.widget.settings.yamlform_entity_reference_autocomplete:
  type: mapping
  label: 'Form autocomplete display format settings'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Placeholder'

field.formatter.settings.yamlform_entity_reference_entity_view:
  type: mapping
  label: 'Display the referenced form with default submission data.'

field.formatter.settings.yamlform_entity_reference_link:
  type: mapping
  label: 'Display the referenced form as a link.'
  mapping:
    label:
      type: label
      label: 'Link label to the referenced form'
