<?php

/**
 * @file
 * Quote block type.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_background_colour.
 *
 * @see options_allowed_values()
 */
function cr_quote_field_background_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.colours.colour_service')->getStandardColoursArray();
}

/**
 * Options callback for field_author_background_colour.
 *
 * @see options_allowed_values()
 */
function cr_quote_field_author_background_colour(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.colours.colour_service')->getStandardColoursArray();
}
