<?php

/**
 * @file
 * Module: cr_google_tag  .
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_page_attachments().
 */
function cr_google_tag_page_attachments(array &$attachments) {
  $loggedIn = \Drupal::currentUser()->id() === 0 ? 'N' : 'Y';
  $env = empty(Settings::get('environment')) ? 'dev' : Settings::get('environment');

  if (isset($_COOKIE['email_address'])) {
   $email_value = $_COOKIE['email_address'];
    print($email_value);
  } else {
    $email_value = 'no value yet'
    print('no email');
  }

  $script = <<<EOS
var dataLayer = window.dataLayer = window.dataLayer || [];
dataLayer.push({
  'site': {
    'pageCategory': 'content', // content, frost, shop, donate or game.
    'pageSubCategory': ' ', //optional
    'environment': '$env'
  },
  'user': {
    'loggedIn': '$loggedIn'
  }
});
EOS;

  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => $script,
    ],
    'cr_google_tag',
  ];

}
