plugin.plugin_configuration.search_api_backend.search_api_solr:
  type: config_object
  label: 'Search API Solr settings'
  mapping:
    scheme:
      type: string
      label: 'The HTTP protocol to use for sending queries'
    host:
      type: string
      label: 'The host name or IP of the Solr server'
    port:
      type: string
      label: 'The port of the Solr server'
    path:
      type: string
      label: 'The path of the Solr server'
    core:
      type: string
      label: 'The name that identifies the Solr core to use on the server'
    excerpt:
      type: boolean
      label: 'Return an excerpt for all results'
    retrieve_data:
      type: boolean
      label: 'Retrieve result data from Solr'
    highlight_data:
      type: boolean
      label: 'Highlight retrieved data'
    skip_schema_check:
      type: boolean
      label: 'Skip schema verification'
    username:
      type: string
      label: 'Username for basic HTTP authentication'
    password:
      type: string
      label: 'Password for basic HTTP authentication'
    excerpt:
      type: integer
      label: 'User to authenticate Solr with'
    retrieve_data:
      type: integer
      label: 'Get data from the solr fields'
    highlight_data:
      type: integer
      label: 'Highlight search string in snippets'
    skip_schema_check:
      type: integer
      label: 'Do not validate if the schema is correct.'
    http_method:
      type: string
      label: 'Use Get or Post for the Solr Queries'
    site_hash:
      type: boolean
      label: 'Restrict searches to current site'
    solr_version:
      type: string
      label: 'Solr version override'
    http_method:
      type: string
      label: 'The HTTP method to use for sending queries'
    autocorrect_spell:
      type: boolean
      label: 'Use spellcheck for autocomplete suggestions'
    autocorrect_suggest_words:
      type: boolean
      label: 'Suggest additional words'
