<?php

/**
 * @file
 * Story row paragraph type.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_cr_story_row_bg_col.
 *
 * @see options_allowed_values()
 */
function cr_story_field_cr_story_row_bg_col(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.colours.colour_service')->getStandardColoursArray();
}

/**
 * Options callback for field_cr_story_fundraiser_bg_col.
 *
 * @see options_allowed_values()
 */
function cr_story_field_cr_story_fundraiser_bg_col(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'bg--red' => t('Red'),
    'bg--blue' => t('Blue'),
    'bg--yellow' => t('Yellow'),
    'bg--pink' => t('Pink'),
    'bg--white' => t('White'),
  ];
  return $values;
}
