<?php

/**
 * @file
 * Cards row paragraph type.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Options callback for field_cr_cards_background.
 *
 * @see options_allowed_values()
 */
function cr_cards_field_cr_cards_background(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  return \Drupal::service('cr.colours.colour_service')->getStandardColoursArray();
}

/**
 * Options callback for field_cr_card_background.
 *
 * @see options_allowed_values()
 */
function cr_card_field_cr_card_background(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
    return \Drupal::service('cr.colours.colour_service')->getStandardColoursArray();
}

/**
 * Options callback for field_cr_cards_grid.
 *
 * @see options_allowed_values()
 */
function cr_cards_field_cr_cards_grid(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL) {
  $values = [
    'cards--four-grid' => t('1/4 width left'),
    'cards--four-grid-centre' => t('1/4 width centre'),
    'cards--three-grid' => t('1/3 width left'),
    'cards--three-grid-centre' => t('1/3 width centre'),
    'cards--two-grid' => t('1/2 width centre'),
  ];
  return $values;
}
