# Schema for the configuration files of the CookieConsent module.

cookieconsent.settings:
  type: config_object
  label: 'Cookie settings'
  translatable: true
  mapping:
    headline_text:
      type: text
      label: 'This website uses cookies to ensure you get the best experience on our website'
    accept_button_text:
      type: text
      label: 'Got it!'
    read_more_button_text:
      type: text
      label: 'More info'
